=== charlesbrandontheis/persephone/_attachments/schema/v3.00.schema.json
{

  "$schema": "http://json-schema.org/draft-04/schema#",

  "description": "MADF 3.0",

  "id": "/",

  "type": "object",

  "definitions": {

    "contact": {
      "type": "object",
      "properties": {
        "name":    { "type": "string" },
        "contact": { "type": "string" }
      }
    },

    "result_measurement": {
      "type": "object",
      "properties": {
        "type":    { "enum": ["measurement"] },
        "isotope": { "type": "string" },
        "unit":    { "enum": ["pct", "ppm", "ppb", "ppt",
                              "ppq", "Bq/kg", "mBq/kg",
                              "uBq/kg", "\u00B5Bq/kg",
                              "nBq/kg", "mBq", "muBq/m",
                              "ng/cm", "pg/cm2", "ea"] },
        "value": {
				  "type": "array",
				  "minItems": 1, "maxItems": 3,
          "items": {
            "type": "number"
          }
        }
      },
      "required": ["type", "isotope", "unit", "value"]
    },

    "result_range": {
      "type": "object",
      "properties": {
        "type":    { "enum": ["range"] },
        "isotope": { "type": "string" },
        "unit":    { "enum": ["pct", "ppm", "ppb", "ppt",
                              "ppq", "Bq/kg", "mBq/kg",
                              "uBq/kg", "\u00B5Bq/kg",
                              "nBq/kg", "mBq", "muBq/m",
                              "ng/cm", "pg/cm2", "ea"] },
        "value": {
				  "type": "array",
				  "minItems": 1, "maxItems": 3,
          "items": {
            "type": "number"
          }
        }
      },
      "required": ["type", "isotope", "unit", "value"]
    },

    "result_limit": {
      "type": "object",
      "properties": {
        "type":    { "enum": ["limit"] },
        "isotope": { "type": "string" },
        "unit":    { "enum": ["pct", "ppm", "ppb", "ppt",
                              "ppq", "Bq/kg", "mBq/kg",
                              "uBq/kg", "\u00B5Bq/kg",
                              "nBq/kg", "mBq", "muBq/m",
                              "ng/cm", "pg/cm2", "ea"] },
        "value": {
          "type": "array",
          "minItems": 1, "maxItems": 2,
          "items": {
            "type": "number"
          }
        }
      },
      "required": ["type", "isotope", "unit", "value"]
    },

    "user": {
  		"type": "object",
      "properties": {
        "name":        { "type": "string" },
        "description": { "type": "string" },
        "type":        { "type": "string" },
        "value":       {
          "oneOf": [
            { "type": "string" },
            { "type": "number" }
          ]
        },
        "unit":        { "type": "string" }
      },
      "required": ["name", "type"]
    }

  },

  "properties": {

    "specification": { "type": "string" },

    "grouping":      { "type": "string" },

    "type":          { "type": "string" },

    "measurement": {
      "type": "object",
      "properties": {
        "requestor":    { "$ref": "#/definitions/contact" },
        "practitioner": { "$ref": "#/definitions/contact" },
        "technique":    { "type": "string" },
        "institution":  { "type": "string" },
        "date": {
					"type": "array",
					"minItems": 0, "maxItems": 2,
					"items": {
            "anyOf" : [
              { "type": "string", "pattern": "[0-9]{4}-[0-9]{2}-[0-9]{2}" },
              { "type": "string", "pattern": "[0-9]{4}-[0-9]{2}" },
              { "type": "string", "pattern": "[0-9]{4}" }
            ]
				  }
				},
        "results": {
					"type": "array",
					"items": {
            "oneOf" : [
              { "$ref": "#/definitions/result_measurement" },
              { "$ref": "#/definitions/result_range" },
              { "$ref": "#/definitions/result_limit" }
            ]
          }
				},
        "user": { "$ref": "#/definitions/user" }
			}
    },

    "sample": {
      "type": "object",
      "properties": {
        "name":        { "type": "string" },
        "description": { "type": "string" },
        "id":          { "type": "string" },
        "source":      { "type": "string" },
        "owner":       { "$ref": "#/definitions/contact" },
        "user":        { "$ref": "#/definitions/user" }
      },
      "required": ["name", "description"]
    },

    "data_source": {
      "type": "object",
      "properties": {
        "input": {
          "type": "object",
          "properties": {
            "date":    {
              "type": "string",
              "pattern":"[0-9]{4}-[0-9]{2}-[0-9]{2}"
						},
            "name":    { "type": "string" },
            "contact": { "type": "string" }
          },
          "required": ["name", "contact", "date"]
        },
        "reference": { "type": "string" },
        "notes":     { "type": "string" },
        "user":      { "$ref": "#/definitions/user" }
      }
    }

  },

  "required": ["grouping", "specification", "type",
               "sample", "data_source", "measurement"]

}

=== charlesbrandontheis/persephone/doc/data_specification/example_assays/example_v2.01_minimal.json
{

  "type":                   "measurement",

  "grouping":               "0vBB Experiment",

  "sample": {
    "name":                 "Plombum, VG3 lead (extra special)",
    "description":          "Plombum, VG3 lead (extra special)",
    "id":                   "",
    "source":               "",
    "owner": { 
      "name":                   "", 
      "contact":                "" 
    }
  },

  "measurement": {
    "institution":          "Low-background Facility",
    "technique":            "Gamma",
    "date":                ["2000-05-02"],
    "requestor": { 
      "name":                   "", 
      "contact":                "" 
    },
    "practitioner": { 
      "name":                   "", 
      "contact":                "" 
    },
    "description":          "", 
    "results": []
  },

  "data_source": {
    "reference":            "0vBB-EXP-0003 (Technical report)",
    "input": { 
      "name":                   "Eve Undergraduate", 
      "contact":                "eve@university.edu",
      "date":                   "2010-01-01"                
    },
    "notes":                "Source report is somewhat uniformative - pages missing?"    
  },

  "specification":          "2.01"

}

=== charlesbrandontheis/persephone/doc/example_assays/example_v2.01_basic.json
{

  "type":                   "measurement",

  "grouping":               "0vBB Experiment",

  "sample": {
    "name":                 "Plombum, VG2 lead",
    "description":          "Plombum, VG2 lead, lot #D9119",
    "id":                   "Pb-001",
    "source":               "Plombum FL",
    "owner": { 
      "name":                   "Alice Professor, A University", 
      "contact":                "alice@university.edu" 
    }
  },

  "measurement": {
    "institution":          "Low-background Facility",
    "technique":            "Gamma",
    "date":                 ["2000-01-02"],
    "requestor": { 
      "name":                   "Alice Professor, A University", 
      "contact":                "alice@university.edu" 
    },
    "practitioner": { 
      "name":                   "Bob Technician", 
      "contact":                "bob@lowbackground.edu" 
    },
    "description":          "Standard gamma count of the whole brick.", 
    "results": [
      { "isotope":"Th-232", "type":"range",       "value":[3.2,4.2], "unit":"ppb" },
      { "isotope":"U-238",  "type":"measurement",       "value":[30],      "unit":"ppb" },
      { "isotope":"K",      "type":"limit", "value":[170,10],  "unit":"ppt" },
      { "isotope":"Co-60",  "type":"measurement", "value":[270,40],  "unit":"ppt" }
    ]
  },

  "data_source": {
    "reference":            "0vBB-EXP-0001 (Technical report)",
    "input": { 
      "name":                   "Eve Undergraduate", 
      "contact":                "eve@university.edu",
      "date":                   "2010-01-01"                
    },
    "notes":                "There seems to be a typo in the results list in the report. Interperate U-239 as U-238."    
  },

  "specification":          "2.01"

}
